# Generated by Django 4.2.27 on 2025-12-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('emergency', 'Emergency')], default='regular', max_length=20)),
                ('reason', models.TextField()),
                ('out_datetime', models.DateTimeField()),
                ('in_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('used', 'Used')], default='pending', max_length=20)),
                ('approver_comment', models.TextField(blank=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_passes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='gate_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gate Pass',
                'verbose_name_plural': 'Gate Passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OUT', 'Exit'), ('IN', 'Entry')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gate_pass.gatepass')),
                ('marked_by', models.ForeignKey(limit_choices_to={'role': 'security'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gate Log',
                'verbose_name_plural': 'Gate Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
