# Generated by Django 4.2.27 on 2025-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_pass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='type',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='pass_type',
            field=models.CharField(choices=[('DAY_OUT', 'Day Out'), ('HOME_LEAVE', 'Home Leave'), ('EMERGENCY', 'Emergency'), ('NIGHT_OUT', 'Night Out'), ('LONG_LEAVE', 'Long Leave')], default='DAY_OUT', max_length=20),
        ),
    ]
