# Generated by Django 4.2.27 on 2025-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='residency_type',
            field=models.CharField(choices=[('DAY_SCHOLAR', 'Day Scholar'), ('HOSTELLER', 'Hosteller')], default='DAY_SCHOLAR', max_length=15),
        ),
    ]
