# Generated by Django 4.2.27 on 2025-12-07 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_residency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('CAI', 'Computer Science & AI'), ('CSD', 'Computer Science & Data Science'), ('EEE', 'Electrical & Electronics Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('MEC', 'Mechanical Engineering'), ('CIV', 'Civil Engineering'), ('H&S', 'Humanities & Sciences')], max_length=10),
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('CAI', 'Computer Science & AI'), ('CSD', 'Computer Science & Data Science'), ('EEE', 'Electrical & Electronics Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('MEC', 'Mechanical Engineering'), ('CIV', 'Civil Engineering'), ('H&S', 'Humanities & Sciences')], max_length=10)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('academic_year', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incharge', models.ForeignKey(limit_choices_to={'role__in': ['class_incharge', 'faculty']}, on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Assignment',
                'verbose_name_plural': 'Class Assignments',
                'unique_together': {('department', 'year', 'section', 'semester', 'academic_year')},
            },
        ),
    ]
